### ISSUE TITLE
Github Reviews list 1 but none in page

### ISSUE THREAD

**Issue by Callek** [mikeconley/myqonly#12]
![image](https://user-images.githubusercontent.com/1415602/47161122-5a472a80-d2bf-11e8-8ea8-ede3abc99883.png)

**Comment by Callek** [comment]
I found https://github.com/mozilla-releng/treescript/pull/24 which could very well be confusion here...

**Comment by mikeconley** [comment]
Huh. Does our query need fiddling, @thomcc?

**Comment by Callek** [comment]
Looks like the reviews page on github (for me) has ` archived:false ` as an added constrictor, but I don't see that in https://github.com/mikeconley/myqonly/blob/788cfc1ff35f2aa2c5f3b54df522d5836f99c730/background.js#L121

**Comment by thomcc** [comment]
Ah, yep, that seems reasonable, sorry.

**Comment by mikeconley** [comment]
Fixed in b3c53c1
