### ISSUE TITLE
Addon says I have one (1) review, but it lies

### ISSUE THREAD

**Issue by snorp** [mikeconley/myqonly#14]
![phab-dashbaord](https://user-images.githubusercontent.com/31482/47221397-d30abd00-d379-11e8-9ee7-77cc60a3b89d.png)

**Comment by snorp** [comment]
I restarted my Nightly and the addon badge went away. Maybe some kind of problem with updating?

**Comment by mikeconley** [comment]
> I restarted my Nightly and the addon badge went away. Maybe some kind of problem with updating?

Yeah, an updating problem sounds likely. :/ Sorry about that.

I'll add some diagnostic goop to the next version, and if it happens again, I might ask for some of that goop back.

**Comment by gcp** [comment]
Same issue here. Wonder if it's related to the bug have other reviwers? Did went away after a restart.

**Comment by mikeconley** [comment]
Has this bug recurred for anybody since it was originally reported?

**Comment by zoepage** [comment]
I see the update issue, just the other way around. So, I have reviews in my queue, but don't see the notification.

**Comment by mikeconley** [comment]
> I see the update issue, just the other way around. So, I have reviews in my queue, but don't see the notification.

Hey @zoepage,

Alright, let's see if we can debug what's going wrong here. I've added some tools to try to diagnose things like this - hopefully they work!

If you're in the bugged state, can you please:

1. Click on the MyQOnly button, and click the gear icon to enter the Options UI
2. Move your mouse cursor to the bottom right - there's a hidden "Debug" link fixed to the bottom right corner. Please click it.
3. In the interface that comes up, click on "Check for updates now", and ensure that the count is still not correct in the MyQOnly icon. If so, move on to 4.
4. Click on "Generate Phabricator test for current user state". If all goes well, a chunk of HTML will show up in the text box underneath it.

Can you please copy that text and email it to me at mconley at mozilla dot com? It _should_ be sanitized, but I want to make sure by hand (this is the first time I've had to use these tools in the wild).

**Comment by zoepage** [comment]
Mail is out. LMK, if I can help with anything else.

**Comment by mikeconley** [comment]
@zoepage and I have sorted this out over e-mail, and the bug appears to be gone for now.

I'm going to close this one out. Please let's re-open it if someone else sees something similar.
