### ISSUE TITLE
Add manual refresh ability

### ISSUE THREAD

**Issue by Callek** [mikeconley/myqonly#16]
It would be nice if I could set a longer timeout but still have a link for manual refresh... e.g. I set a 1 min refresh right now, but in reality a 10 or 20 minute refresh is all I need, but an occasional "I'm between tasks, let me see if I have any new ones" button would be useful.

**Comment by mikeconley** [comment]
Added in 0266b9d66c8cfe0d8191ae2111c3fb3980a85a13.
