### ISSUE TITLE
No warnings if you're signed out

### ISSUE THREAD

**Issue by Standard8** [mikeconley/myqonly#19]
Firefox decided to sign me out of phab/bugzilla. When I started up I knew I had reviews, so was going to use the button for a shortcut to get to them, but it said "No reviews to do! \o/".

It feels like we should have a warning if you're signed out.

Note that in the phabricator signed-out case, https://phabricator.services.mozilla.com/differential/query/active/ was returning a 404.

**Comment by mikeconley** [comment]
This was fixed in 0.6.
