### ISSUE TITLE
grammar nit: "1 reviews on Github"

### ISSUE THREAD

**Issue by 6a68** [mikeconley/myqonly#25]
Should be "1 review on Github", singular:

<img width="245" alt="screen shot 2019-01-03 at 1 24 29 pm" src="https://user-images.githubusercontent.com/96396/50662385-09101400-0f5b-11e9-96ea-7a3b761afded.png">

I'm seeing this on version 0.6.1, which Firefox tells me is the latest :+1:

**Comment by mikeconley** [comment]
Thanks!

I worked around this in 0.7 by using "review(s)" and "needinfo(s)".

I might try to see if I can use Fluent for this WebExtension, which might get me some of that plural-form stuff for free.

**Comment by 6a68** [comment]
haha, nice hack!
