### ISSUE TITLE
Pop-up window is blank

### ISSUE THREAD

**Issue by gcp** [mikeconley/myqonly#30]
![myqonly](https://user-images.githubusercontent.com/1104290/56889926-2a4fbf80-6a78-11e9-930e-d537de059d93.png)

The content is there, I can click on it. Sometimes the contents of the window is rendered, but usually it is not.

This could well be a Firefox bug (reminds me of bug 1408446) but I don't see it with other add-ons like uBlock Origin. Also not sure where to file!

**Comment by mikeconley** [comment]
This might actually be [this WebExtension API bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1512998). Do you notice the issue is more prevalent if you're click-holding the icon more than a short interval?

**Comment by gcp** [comment]
Yep, that seems to be correlated.
