### ISSUE TITLE
Allow displaying Github reviews

### ISSUE THREAD

**Issue by ncalexan** [mikeconley/myqonly#5]
I do some of my work in mozilla-central (which means BZ and Phab reviews) but a lot of my work in github.com/mozilla/application-services, for example (which means GH reviews).  Can we generalize to a third system?

**Comment by mikeconley** [comment]
I'm all for it.

[GitHub's API documentation is here](https://developer.github.com/v3/). [Here's the section on Pull Requests](https://developer.github.com/v3/pulls/review_requests/#list-review-requests). A quick glance doesn't show a quick and easy way of getting the list of open pull requests for a user across repositories, so we might need to first query for the repository list, and then ask each of them for an open pull request count.

It might be possible to work with the [Notification API](https://developer.github.com/v3/activity/notifications/) to get that information as well.

**Comment by ncalexan** [comment]
This information is already present, per-user, in https://github.com/pulls/review-requested so surely we can either use the API or scrape that.

**Comment by thomcc** [comment]
Their [v4 API](https://developer.github.com/v4/) is GraphQL based, which IIUC allows getting this stuff without scraping, even if the REST API doesn't support it. There's even a neat tool to try queries with: https://developer.github.com/v4/explorer/

**Comment by 6a68** [comment]
Found a stackoverflow answer with the correct snippet (just need to sub in the user for 'refack'): https://stackoverflow.com/questions/48255251/how-to-query-review-requests-by-user-using-githubs-v4-graphql-api
